config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	#валидания на заполнение полей
	validates :title,:body,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # метод просмотра постов
  def index
    @posts = Post.all
  end

  # перенаправление на создание нового поста
  def new
  end

  # создание поста
  def create
 	  @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  # просмотр поста
  def show
    @post = Post.find(params[:id])
  end

  #редактирование поста
  def edit
    @post = Post.find(params[:id])
  end

  #обновление поста
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  #удаление поста
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  #получение параметров поста
  private
    def post_params
      params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BlogOnRor</title>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container container_header">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">RoR Blog</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Blog</a></li>
            <li><a href="/posts/new">New Post</a></li>		
          </ul>
        </div>
      </div>
    </div>
    <div class="container container_blog">
      <%= yield %>
    </div>
</body>
</html>

app/views/posts/edit.html.erb
<h2 class="edit-block-center">Edit Post</h2>
<a href="/ %>" class=" btn btn-success ">Back to Post</a>
<br><br>
<!-- форма редактирование записи -->
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <!-- контейнер ошибок -->
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <!-- контейнер редактирования содержимого записи -->
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body , :rows => "10"%>
    </p>
    <p class="pcenter">
      <%= f.submit "Update" , :class => "btn btn-success"%>
      <%= link_to 'Delete', post_path(@post),
           method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-success " %>
    </p>
<% end %>

app/views/posts/index.html.erb
<ul>
<!-- форма отображение всех постов -->
<% @posts.each do |post| %>
 <li >
 <!--  отображение каждого поста -->
   <h1 class="t-align">   
    <%= post.title %>
    <%= link_to 'Delete', post_path(post),
           method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-success home-link" %>
   <%= link_to 'Edit', edit_post_path(post) , :class => "btn btn-success home-link" %>  
   <%= link_to 'Show', post, :class => "btn btn-success home-link "  %>
   </h1>      
 </li>
 <hr>
<% end %>
</ul>

app/views/posts/new.html.erb
<h2 class="edit-block-center">Create Post</h2>
<a href="/>" class=" btn btn-success">Back to Blog</a>
<br><br>
<!-- форма создания записи -->
<%= form_for :post, url: posts_path   do |f| %>  
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>   
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body , :rows => "10"%>
    </p>   
    <p>
      <%= f.submit "Create" , :class => "btn btn-success center"%>
    </p>
<% end %>

app/views/posts/show.html.erb
<!-- контейнер просмотра записи -->
<div class="block-center">
	<h1><%= @post.title %></h1>
	<a href="/" class="btn btn-success">Back to Blog</a>
	<%= link_to 'Edit', edit_post_path(@post),:class => "btn btn-success " %>	
	<%= link_to 'Delete', post_path(@post),
           method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-success " %>
</div>
<br>
<p><%= @post.body %></p>